// Author: Lucas Oliveira Vilas-Bôas
// Year: 2023
// Repository: https://github.com/lucoiso/PasswordManagement

import "ModuleInterface.idl";

namespace MainApplication
{
    [default_interface]
    runtimeclass LoginDataListItem : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        LoginDataListItem();

        LoginData Data;
        String Password{ get; };

        String TimeCreated{ get; };
        String TimeUsed{ get; };
        String TimeChanged{ get; };
    }
}