// Author: Lucas Oliveira Vilas-Bôas
// Year: 2023
// Repository: https://github.com/lucoiso/PasswordManagement

import "ModuleInterface.idl";

namespace MainApplication
{
    [default_interface]
    runtimeclass LoginDataListView : Microsoft.UI.Xaml.Controls.UserControl
    {
        LoginDataListView();

        Boolean EnableLicenseTools;

        void InsertDataInList(PasswordManager.LoginData data);
        void RemoveDataFromList(PasswordManager.LoginData data);
        void RemoveAllDataFromList();

        Windows.Foundation.Collections.IObservableVector<PasswordManager.LoginData> FilteredData{ get; };
        Windows.Foundation.Collections.IVector<PasswordManager.LoginData> Data{ get; };

		void Sort(DataSortMode mode, DataSortOrientation orientation);
    }
}
