// Author: Lucas Oliveira Vilas-Bôas
// Year: 2023
// Repository: https://github.com/lucoiso/PasswordManagement

import "ModuleInterface.idl";

namespace MainApplication
{
    [default_interface]
    runtimeclass LoginDataListMenu : Microsoft.UI.Xaml.Controls.UserControl
    {
        LoginDataListMenu();

        Boolean EnableLicenseTools;
   
        DataSortMode SelectedSortingMode{ get; };        
        DataSortOrientation SelectedSortingOrientation{ get; };

        event MainApplication.SingleVoidDelegate ImportPressed;
        event MainApplication.ExportTypeDelegate ExportPressed;

        event MainApplication.SingleVoidDelegate SortingChanged;
    }
}
