// Author: Lucas Oliveira Vilas-Bôas
// Year: 2022
// Repository:

namespace MainApplication
{
    [default_interface]
    runtimeclass LoginDataTypeComboBox : Microsoft.UI.Xaml.Controls.UserControl
    {
        LoginDataTypeComboBox();

        String SelectedOption{ get; };
        Windows.Foundation.Collections.IObservableVector<String> Options{ get; };
    }
}
