// Author: Lucas Oliveira Vilas-Bôas
// Year: 2022
// Repository: https://github.com/lucoiso/PasswordManagement

import "ModuleInterface.idl";

namespace MainApplication
{
    [default_interface]
    runtimeclass LoginDataListView : Microsoft.UI.Xaml.Controls.UserControl
    {
        LoginDataListView();

        void InsertDataInList(PasswordManager.LoginData data);
        Windows.Foundation.Collections.IObservableVector<PasswordManager.LoginData> FilteredData{ get; };
        Windows.Foundation.Collections.IVector<PasswordManager.LoginData> Data{ get; };

		void Sort(DataSortMode mode, DataSortOrientation orientation);
    }
}
