// Author: Lucas Oliveira Vilas-Bôas
// Year: 2022
// Repository:

namespace MainApplication
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
    }
}
