// Author: Lucas Oliveira Vilas-Bôas
// Year: 2023
// Repository: https://github.com/lucoiso/PasswordManagement

namespace MainApplication
{
    enum DataSortMode
    {
        Undefined,
        Name,
        Url,
        Username,
        Notes,
        Created,
        Used,
        Changed,
        MAX
    };

    enum DataSortOrientation
    {
        Undefined,
        Ascending,
        Descending,
        MAX
    };

    delegate void SingleVoidDelegate();
    delegate void ExportTypeDelegate(PasswordManager.LoginDataExportType export_type);
}