// Author: Lucas Oliveira Vilas-Bôas
// Year: 2023
// Repository: https://github.com/lucoiso/PasswordManagement

namespace PasswordGenerator
{
    [default_interface]
    runtimeclass Generator
    {
        Generator();
        static Windows.Foundation.IAsyncOperation<String> GeneratePassword();
    }
}
