// Author: Lucas Oliveira Vilas-Bôas
// Year: 2023
// Repository: https://github.com/lucoiso/PasswordManagement

namespace PasswordManager
{ 
	enum LoginDataExportType
	{
		Undefined,
		Microsoft,
		Google,
		Firefox,
		Kapersky,
		Lupass,
		GenericCSV,
		MAX
	};

	interface IFunctionalData
	{
		IFunctionalData Clone();
		Boolean Equals(IFunctionalData rhs);
	};

	[default_interface]
	runtimeclass LoginData : IFunctionalData
	{
		LoginData();

		String Name;
		String Url;
		String Username;
		String Password;
		String Notes;

		String GetExportData(LoginDataExportType type);

		Boolean HasEmptyData();
		void ResetLoginData();
	}

	[default_interface]
	runtimeclass LoginUpdateEventParams
	{
		LoginUpdateEventParams(LoginData data, LoginDataExportType type);

		LoginData Data{ get; };
		LoginDataExportType Type{ get; };
	};

	[default_interface]
	runtimeclass LoginDataManager
	{
		LoginDataManager();

		Windows.Foundation.IAsyncAction ImportDataAsync(Windows.Storage.StorageFile file, LoginDataExportType export_type);
		Windows.Foundation.IAsyncAction ExportDataAsync(Windows.Storage.StorageFile file, Windows.Foundation.Collections.IVectorView<LoginData> data, LoginDataExportType type);

		event Windows.Foundation.EventHandler<LoginUpdateEventParams> LoginDataUpdated;
	}
}