// Author: Lucas Oliveira Vilas-Bôas
// Year: 2023
// Repository: https://github.com/lucoiso/PasswordManagement

namespace PasswordManager
{
    enum LoginDataFileType
    {
        Undefined,
        Microsoft,
        Google,
        Firefox,
        Kapersky,
        Lupass_Internal,
        Lupass_External,
        GenericCSV,
        MAX
    };

    interface IFunctionalData
    {
        IFunctionalData Clone();
        Boolean Equals(IFunctionalData rhs);
    };

    [default_interface]
    runtimeclass LoginData : IFunctionalData
    {
        LoginData();

        String Name;
        String Url;
        String Username;
        String Password;
        String Notes;

        UInt64 Created;
        UInt64 Changed;
        UInt64 Used;

        void InitializeInvalidTimes();
        String GetExportData(LoginDataFileType type);

        Boolean HasEmptyData();
        void ResetLoginData();
    }

    [default_interface]
    runtimeclass LoginUpdateEventParams
    {
        LoginUpdateEventParams(Windows.Foundation.Collections.IVector<LoginData> data, LoginDataFileType type);

        Windows.Foundation.Collections.IVectorView<LoginData> Data{ get; };
        LoginDataFileType Type{ get; };
    };

    [default_interface]
    runtimeclass LoginDataManager
    {
        LoginDataManager();

        Windows.Foundation.IAsyncAction ImportDataAsync(Windows.Storage.StorageFile file, LoginDataFileType import_type);
        Windows.Foundation.IAsyncAction ExportDataAsync(Windows.Storage.StorageFile file, Windows.Foundation.Collections.IVectorView<LoginData> data, LoginDataFileType type);

        event Windows.Foundation.EventHandler<LoginUpdateEventParams> LoginDataUpdated;
    }
}